-- CREATE TABLE IF NOT EXISTS companies (
--                                          id BIGINT AUTO_INCREMENT PRIMARY KEY,
--                                          name VARCHAR(255) NOT NULL UNIQUE,
--     logo VARCHAR(500),
--     industry VARCHAR(100) NOT NULL,
--     size VARCHAR(50) NOT NULL,
--     rating DECIMAL(2,1) NOT NULL CHECK (rating >= 0.0 AND rating <= 5.0),
--     locations VARCHAR(1000),
--     description TEXT,
--     founded INT NOT NULL,
--     employees INT,
--     website VARCHAR(500),
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
--     created_by VARCHAR(20) NOT NULL,
--     updated_at TIMESTAMP DEFAULT NULL,
--     updated_by VARCHAR(20) DEFAULT NULL
--     );